# Site settings
title: DevOps Cape Town
email: organisers@devops.capetown
description: >
  DevOps Cape Town is a community group interested in advancing the adoption and evolution of DevOps in their home city

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://devops.capetown"

# Social media
github_username:  cpt-devops
twitter_username: cpt_devops
youtube_channel: UCuu8jzt29J5rfGvo1cBiuog

# Build settings
markdown: kramdown
exclude: [deploy.sh, Gemfile, Gemfile.lock, README.md, vendor]

# vim: set ts=2 sts=2 sw=2 et:
